version: "3.9"
services:
  server:
    image: checker/server
    hostname: server
    ports:
        - "7000:7000"
    build: 
      context: .
      dockerfile: server.Dockerfile
      args: 
        REPO: "https://github.com/JSalmen13/holbertonschool-web_front_end/tree/master/0x06-responsive_design"
        FOLDER: "0x06-responsive_design"
    logging: 
      driver: none
  testing:
    image: checker/tester
    build: 
      context: .
    ports: 
      - "5500:5500"
    depends_on:
      - server
  